// GENERATED by tools/gen_heuristics.py from server/shieldlib/engine.py. Do not edit by hand.
export default {
 "brands": {
  "paypal": [
   "paypal.com",
   "paypal.me"
  ],
  "apple": [
   "apple.com",
   "icloud.com",
   "me.com"
  ],
  "icloud": [
   "icloud.com",
   "apple.com"
  ],
  "microsoft": [
   "microsoft.com",
   "live.com",
   "outlook.com",
   "office.com",
   "microsoftonline.com",
   "office365.com"
  ],
  "office365": [
   "office.com",
   "microsoft.com",
   "office365.com"
  ],
  "outlook": [
   "outlook.com",
   "live.com",
   "microsoft.com"
  ],
  "amazon": [
   "amazon.com",
   "amazon.co.uk",
   "amazon.de",
   "amazon.fr",
   "amazon.ca",
   "amazon.in",
   "amazon.it",
   "amazon.es",
   "amazon.co.jp",
   "amazon.com.au",
   "amazon.jobs"
  ],
  "google": [
   "google.com",
   "gmail.com",
   "youtube.com"
  ],
  "gmail": [
   "gmail.com",
   "google.com"
  ],
  "netflix": [
   "netflix.com"
  ],
  "facebook": [
   "facebook.com",
   "fb.com",
   "meta.com",
   "facebookmail.com"
  ],
  "instagram": [
   "instagram.com"
  ],
  "whatsapp": [
   "whatsapp.com",
   "whatsapp.net",
   "wa.me"
  ],
  "telegram": [
   "telegram.org",
   "t.me"
  ],
  "dhl": [
   "dhl.com",
   "dhl.de",
   "dhl.co.uk"
  ],
  "fedex": [
   "fedex.com"
  ],
  "usps": [
   "usps.com"
  ],
  "ups": [
   "ups.com"
  ],
  "irs": [
   "irs.gov"
  ],
  "hmrc": [
   "gov.uk"
  ],
  "chase": [
   "chase.com"
  ],
  "wellsfargo": [
   "wellsfargo.com"
  ],
  "bankofamerica": [
   "bankofamerica.com"
  ],
  "coinbase": [
   "coinbase.com"
  ],
  "binance": [
   "binance.com"
  ],
  "metamask": [
   "metamask.io"
  ],
  "steam": [
   "steampowered.com",
   "steamcommunity.com"
  ],
  "docusign": [
   "docusign.com",
   "docusign.net"
  ],
  "dropbox": [
   "dropbox.com"
  ],
  "linkedin": [
   "linkedin.com"
  ],
  "rbc": [
   "rbc.com",
   "rbcroyalbank.com",
   "royalbank.com"
  ],
  "royalbank": [
   "rbc.com",
   "rbcroyalbank.com",
   "royalbank.com"
  ],
  "td": [
   "td.com",
   "tdcanadatrust.com",
   "tdbank.com"
  ],
  "tdcanadatrust": [
   "td.com",
   "tdcanadatrust.com"
  ],
  "bmo": [
   "bmo.com"
  ],
  "scotiabank": [
   "scotiabank.com",
   "scotiaonline.scotiabank.com"
  ],
  "scotia": [
   "scotiabank.com"
  ],
  "cibc": [
   "cibc.com"
  ],
  "desjardins": [
   "desjardins.com"
  ],
  "tangerine": [
   "tangerine.ca"
  ],
  "simplii": [
   "simplii.com"
  ],
  "eqbank": [
   "eqbank.ca"
  ],
  "vancity": [
   "vancity.com"
  ],
  "coastcapital": [
   "coastcapitalsavings.com"
  ],
  "nationalbank": [
   "nbc.ca"
  ],
  "interac": [
   "interac.ca"
  ],
  "etransfer": [
   "interac.ca"
  ],
  "wealthsimple": [
   "wealthsimple.com"
  ],
  "koho": [
   "koho.ca"
  ],
  "cra": [
   "canada.ca",
   "gc.ca"
  ],
  "canadapost": [
   "canadapost.ca",
   "canadapost-postescanada.ca"
  ],
  "visa": [
   "visa.com",
   "visa.ca"
  ],
  "mastercard": [
   "mastercard.com",
   "mastercard.ca"
  ]
 },
 "shorteners": [
  "bit.do",
  "bit.ly",
  "buff.ly",
  "cutt.ly",
  "goo.gl",
  "is.gd",
  "ow.ly",
  "qrco.de",
  "rb.gy",
  "rebrand.ly",
  "s.id",
  "shorte.st",
  "shorturl.at",
  "t.co",
  "t.ly",
  "tiny.cc",
  "tinyurl.com",
  "v.gd"
 ],
 "riskyTlds": [
  "bond",
  "buzz",
  "cam",
  "cf",
  "cfd",
  "click",
  "country",
  "cyou",
  "download",
  "fun",
  "ga",
  "gq",
  "help",
  "icu",
  "live",
  "loan",
  "lol",
  "ml",
  "monster",
  "mov",
  "online",
  "quest",
  "rest",
  "review",
  "sbs",
  "shop",
  "site",
  "support",
  "tk",
  "top",
  "win",
  "work",
  "xyz",
  "zip"
 ],
 "suspiciousWords": "(login|log-in|signin|sign-in|verify|verification|secure|account|update|confirm|wallet|unlock|recover|billing|webscr|password|auth)",
 "twoLevelSuffixes": [
  "ac.uk",
  "co.in",
  "co.jp",
  "co.kr",
  "co.nz",
  "co.uk",
  "co.za",
  "com.ar",
  "com.au",
  "com.br",
  "com.cn",
  "com.mx",
  "com.sg",
  "com.tr",
  "gov.uk",
  "net.au",
  "org.uk"
 ],
 "homoglyphs": {
  "0": "o",
  "1": "l",
  "3": "e",
  "4": "a",
  "5": "s",
  "7": "t",
  "8": "b",
  "@": "a",
  "$": "s",
  "!": "i",
  "а": "a",
  "в": "b",
  "е": "e",
  "ё": "e",
  "к": "k",
  "м": "m",
  "н": "h",
  "о": "o",
  "р": "p",
  "с": "c",
  "т": "t",
  "у": "y",
  "х": "x",
  "і": "i",
  "ї": "i",
  "ј": "j",
  "ѕ": "s",
  "ԁ": "d",
  "ɡ": "g",
  "ο": "o",
  "α": "a",
  "ν": "v",
  "ρ": "p",
  "τ": "t",
  "υ": "u",
  "ι": "i",
  "κ": "k"
 },
 "freeHosting": [
  "amazonaws.com",
  "googleusercontent.com",
  "azurewebsites.net",
  "web.core.windows.net",
  "blob.core.windows.net",
  "github.io",
  "weebly.com",
  "wixsite.com",
  "blogspot.com",
  "web.app",
  "firebaseapp.com",
  "pages.dev",
  "netlify.app",
  "vercel.app",
  "glitch.me",
  "herokuapp.com",
  "000webhostapp.com",
  "sites.google.com",
  "r2.dev",
  "workers.dev"
 ],
 "ipTrick": "(0x[0-9a-f]+|\\d+)(\\.(0x[0-9a-f]+|\\d+)){0,3}",
 "levels": [
  [
   85,
   "critical"
  ],
  [
   60,
   "high"
  ],
  [
   35,
   "medium"
  ],
  [
   15,
   "low"
  ],
  [
   0,
   "safe"
  ]
 ]
};
