"""Generates extension/heuristics-data.js from server/shieldlib/engine.py, so the extension's on-device
link checks use exactly the same brand list, risky TLDs and word lists as the server (one source of truth).

Run after editing those lists:   python tools/gen_heuristics.py
CI runs it with --check and fails if the generated file is out of date.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "server"))
from shieldlib import engine  # noqa: E402

OUT = os.path.join(ROOT, "extension", "heuristics-data.js")


def build():
    data = {
        "brands": engine.BRANDS,
        "shorteners": sorted(engine.SHORTENERS),
        "riskyTlds": sorted(engine.RISKY_TLDS),
        "suspiciousWords": engine.SUSPICIOUS_WORDS.pattern,
        "twoLevelSuffixes": sorted(engine.TWO_LEVEL_SUFFIXES),
        "homoglyphs": {chr(k): v for k, v in engine.HOMOGLYPHS.items()},
        "freeHosting": list(engine.FREE_HOSTING),
        "ipTrick": engine.IP_TRICK_RE.pattern,
        "levels": engine.LEVELS,
        # message analysis (extension/engine.js)
        "textRules": [[c, w, m, rx.pattern] for c, w, m, rx in engine.TEXT_RULES],
        "urlRe": engine.URL_RE.pattern,
        "emailRe": engine.EMAIL_RE.pattern,
        "freeMail": sorted(engine.FREE_MAIL),
    }
    return ("// GENERATED by tools/gen_heuristics.py from server/shieldlib/engine.py. Do not edit by hand.\n"
            "export default " + json.dumps(data, ensure_ascii=False, indent=1, sort_keys=False) + ";\n")


if __name__ == "__main__":
    text = build()
    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current.replace("\r\n", "\n") != text:
            sys.exit("extension/heuristics-data.js is out of date: run python tools/gen_heuristics.py")
        print("heuristics-data.js is up to date")
    else:
        with open(OUT, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print("wrote", os.path.relpath(OUT, ROOT))
