"""Copy the design system (design/*.css) to every place that uses it.

    py tools/sync_design.py

The extension can't load files from the website, so it keeps its own copy.
Never edit the copies - edit the files in design/.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = os.path.join(ROOT, "static", "assets")
EXT = os.path.join(ROOT, "extension", "ui")
# design file -> where it is used
FILES = {
    "tokens.css":     [SITE, EXT],
    "components.css": [SITE, EXT],
    "popup.css":      [SITE, EXT],   # website tutorial shows a replica of the popup
    "overlay.css":    [SITE, EXT],   # ...and of the Card Guard screens
    "site.css":       [SITE],
}
HEADER = "/* GENERATED COPY - edit design/{name} and run py tools/sync_design.py */\n"

for name, targets in FILES.items():
    with open(os.path.join(ROOT, "design", name), encoding="utf-8") as f:
        css = f.read().lstrip("﻿")  # editors on Windows may add a BOM
    for target in targets:
        os.makedirs(target, exist_ok=True)
        with open(os.path.join(target, name), "w", encoding="utf-8") as f:
            f.write(HEADER.format(name=name) + css)
        print("synced", os.path.relpath(os.path.join(target, name), ROOT))


# ---- tour.css: everything the website's practice tutorial needs, in one file, without global rules.
# The tutorial page uses the new site styles (sy.css) for its frame and this file for the replica browser,
# extension popup and Card Guard screens, so the two never fight over body, fonts or link styles.
import re


def read(name):
    with open(os.path.join(ROOT, "design", name), encoding="utf-8") as f:
        return f.read().lstrip("\ufeff")


def without_globals(css):
    return re.sub(r"^\*\s*\{[^}]*\}\s*$", "", css, flags=re.M)  # the `* { box-sizing; font-family }` reset


site = read("site.css")
start = site.index("TUTORIAL")
start = site.rfind("/* ====", 0, start)
end = site.index("@media (prefers-reduced-motion: reduce) { .hotspot")
end = site.index("\n", end) + 1
tutorial = re.sub(r"^\.tut-only[^\n]*\n", "", site[start:end], flags=re.M)
parts = [read("tokens.css"), read("components.css"), without_globals(read("popup.css")), without_globals(read("overlay.css")), tutorial]
out = os.path.join(SITE, "tour.css")
with open(out, "w", encoding="utf-8") as f:
    f.write("/* GENERATED by tools/sync_design.py from design/*.css. Do not edit. */\n" + "\n".join(parts))
print("built", os.path.relpath(out, ROOT))

